name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2

      - name: Set variables
        id: set-variables
        run: |
          echo "::set-output name=aws_s3_bucket::${{ secrets.AWS_BUCKET_NAME }}"
          echo "::set-output name=aws_s3_bucket_region::${{ secrets.AWS_BUCKET_REGION }}"
          echo "::set-output name=aws_access_key_id::${{ secrets.AWS_ACCESS_KEY_ID_PROD }}"
          echo "::set-output name=aws_secret_access_key::${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}"

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # See: https://github.com/actions/cache/blob/main/examples.md#node---yarn
      - name: Get Yarn cache directory
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Use Yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install package dependencies
        run: yarn install --prefer-offline --frozen-lockfile

      - name: Build static website
        run: yarn build

      - name: Upload website to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete --cache-control 'no-store'
        env:
          AWS_S3_BUCKET: ${{ steps.set-variables.outputs.aws_s3_bucket }}
          AWS_ACCESS_KEY_ID: ${{ steps.set-variables.outputs.aws_access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ steps.set-variables.outputs.aws_secret_access_key }}
          AWS_REGION: ${{ steps.set-variables.outputs.aws_s3_bucket_region }}
          SOURCE_DIR: "build"
          
      - name: pin4everland
        id: pin4everland
        uses: 4everland/pin-action@v1.3
        with:
          EVER_TOKEN: ${{secrets.EVER_TOKEN}}
          EVER_PROJECT_NAME: "prep-v2-referral-dashboard"
          EVER_PROJECT_PLAT: "IPFS"
          BUILD_LOCATION: "./build"
